POS.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POS.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

POS.Web/Controllers/OrderController.cs
using POS.Repository;
using POS.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POS.Web.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SelectedProduct(int id)
        {
            Product product = ProductRepo.GetById(id);
            OrderDetail detail = new OrderDetail();

            detail.ProductId = product.Id;
            detail.ProductName = product.Name;
            detail.Price = product.Price;

            return PartialView("_SelectedProduct", detail);
        }
    }
}

POS.Web/Controllers/ProductController.cs
using POS.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POS.Web.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View(ProductRepo.GetAll());
        }

        public ActionResult ProductList()
        {
            return PartialView("_ProductList", ProductRepo.GetAll());
        }
    }
}

POS.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

POS.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

POS.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

POS.Web/Views/Order/Index.cshtml
@{
    ViewBag.Title = "Order";
}

<h2>@ViewBag.Title</h2>
<div class="panel panel-primary">
    <div class="panel panel-heading">
        <input type="button" id="btn-new-order" value="New Order" class="btn btn-success"/>
        <input type="button" id="btn-payment" value="Payment" class="btn btn-primary" />
        <input type="button" id="btn-new-trans" value="New Trans." class="btn btn-danger" />
    </div>
    <div class="panel panel-body">
        <table class="table table-bordered" id="order-table">
            <thead>
                <tr>
                    <th style="width: 40%">Product Name</th>
                    <th style="width: 20%">Price</th>
                    <th style="width: 20%">Quantity</th>
                    <th style="width: 30%">Amount</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @*Order list nanti ada disini*@
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="2">
                        Total
                    </th>
                    <th>
                        <input type="number" value="0" name="tot-qty" class="form-control" />
                    </th>
                    <th>
                        <input type="number" value="0" name="tot-amount" class="form-control"/>
                    </th>
                    <th>Action</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts {
    <script type="text/javascript">
        $("#btn-new-order").click(function () {
            $.ajax({
                url: '@Url.Action("ProductList", "Product")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html('Select product');
                    $(".modal").modal('show');
                }
            })
        })

        function RemoveItem(obj) {
            var tr = $(obj).closest('tr');
            tr.remove();
        }

        function Calculate(obj) {
            var tr = $(obj).closest('tr');

            var prc = tr.find("input[name=Price]").val();
            var qty = tr.find("input[name=Quantity]").val();

            var amount = prc * qty;

            tr.find("input[name=Amount]").val(amount);
        }
    </script>
}

POS.Web/Views/Order/_SelectedProduct.cshtml
@model POS.ViewModel.OrderDetail
<tr>
    <td>
        @Html.HiddenFor(model => model.ProductId)
        @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>
    <td>
        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>
    <td>
        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", @onchange = "Calculate(this)", @onkeyup = "Calculate(this)" } })
    </td>
    <td>
        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>
    <td>
        <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="RemoveItem(this)" title="Select">
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        </button>
    </td>
</tr>

POS.Web/Views/Product/Index.cshtml
@model IEnumerable<POS.ViewModel.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Initial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifyBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifyDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Initial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifyBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifyDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

POS.Web/Views/Product/_ProductList.cshtml
@model IEnumerable<POS.ViewModel.Product>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Initial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Initial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            <button type="button" class="btn btn-success btn-select" data-id="@item.Id" data-dismiss="modal" title="Select">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
        </td>
    </tr>
}

</table>

<script>
    $(".btn-select").click(function () {
        $.ajax({
            url: '@Url.Action("SelectedProduct", "Order")',
            type: 'get',
            data: { id: $(this).attr('data-id') },
            success: function (result) {
                $("#order-table tbody").append(result);
            }
        })
    })
</script>

POS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My POS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("P.O.S", "Index", "Order")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>